### ISSUE TITLE
TextInput readOnly 안 먹힘

### ISSUE THREAD

**Issue by rovxxmjxx** [rubric-dev/parte#57]
TextInput의 readOnly props 안먹히는 버그

**Comment by june6723** [comment]
분석해봤더니 **TextInput**의 문제는 아니고 **react-datepicker**에서 `customInput` props가 작동하는 방식 때문에 생기는 이슈입니다.

https://github.com/Hacker0x01/react-datepicker/blob/master/src/index.jsx#LL1100C3-L1100C18
링크를 가보시면 react-datepicker에서 customInput을 사용할때 input에 어떤 props를 넘겨줘야 할때는 ReactDatePicker에 넘겨주어야 작동 하네요.

그런데 readOnly를 넘겨줄 경우 Calendar dropdown이 아예 열리지가 않아서
해당 [Workaround](https://github.com/Hacker0x01/react-datepicker/issues/1480#issuecomment-574046673)에서
```ts
onFocus={e => e.target.blur()}
```
위와 같이 포커스 주자마자 blur하도록 hack 하라고 하네요 ㅋㅋ 해보니 잘 작동합니다

**Comment by june6723** [comment]
TextInput 무죄 판결 내리도록 하겠습니다 땅땅땅
